name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force bump"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup git app user
        uses: spotdemo4/setup-git-app-user@v2
        id: app
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Bump
        uses: spotdemo4/bumper@main
        with:
          debug: ${{ runner.debug }}
          force: ${{ inputs.force }}
          files: |-
            action.yaml
            .github/README.md
