name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0

      - name: Run checks
        run: nix flake check

  test-nix:
    name: test (nix)
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0
        with:
          shell: check

      - name: Run bumper
        env:
          FORCE: true
          PUSH: false
          DEBUG: ${{ runner.debug }}
        run: bumper tests

      - name: Print diff
        run: git --no-pager diff origin/main

  test-docker:
    name: test (docker)
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run bumper
        uses: spotdemo4/bumper@main
        env:
          force: true
          push: false
          debug: ${{ runner.debug }}

      - name: Print diff
        run: git --no-pager diff origin/main
