name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0

      - name: Run checks
        run: nix flake check

  test-nix:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    name: test (nix)
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0

      - name: Build
        run: nix build -o result

      - name: Run
        env:
          FORCE: true
          PUSH: false
          DEBUG: ${{ runner.debug }}
        run: result/bin/bumper tests

      - name: Print diff
        run: git --no-pager diff origin/main

  test-docker:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    name: test (docker)
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0

      - name: Build
        run: nix build .#image -o result

      - name: Load
        run: docker load -i result

      - name: Run
        env:
          FORCE: true
          PUSH: false
          DEBUG: ${{ runner.debug }}
          PATHS: tests
        uses: docker://bumper:0.6.2

      - name: Print diff
        run: git --no-pager diff origin/main
